# Spring配置（Mail、MySQL、Redis）
spring:
  redis:
    host: dustlight.cn
    port: 30010
  datasource:
    url: jdbc:mysql://dustlight.cn:30020/oauth?characterEncoding=utf8&useSSL=false
    username: hansin
    password: 123456
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 4
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  mail:
    host: smtp.exmail.qq.com
    username: noreply@dustlight.cn
    password: Lb845612500
# 日志输出
logging:
  level:
    cn:
      dustlight:
        uim:
          services:
            ClientMapper: debug
            TemplateManagerMapper: debug
            UserDetailsMapper: debug
# Mybatis 缓存
mybatis-plus:
  configuration:
    cache-enabled: true
    local-cache-scope: session
# 应用配置
dustlight:
  uim:
    csrf-enabled: false
    public-paths:
      - /api/user/**
    resource-paths:
      - /oauth_info
      - /api/res/**
    form-login:
      login-page: /login
      login-processing-url: /api/user/login
    logout:
      logout-url: /api/user/logout
      delete-cookies:
        - SESSION
    register-email: 邮箱验证
    reset-password-email: 密码重置