spring:
  redis:
    host: dustlight.cn
    port: 30010
  datasource:
    url: jdbc:mysql://dustlight.cn:30020/oauth?characterEncoding=UTF-8&useSSL=false
    username: hansin
    password: 123456
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 4
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  mail:
    host: smtp.exmail.qq.com
    username: noreply@dustlight.cn
    password: Lb845612500
dustlight:
  uim:
    csrf-enabled: false
    public-paths:
      - /api/**
    resource-paths:
      - /oauth_info
      - /api/res/**
    form-login:
      login-page: /login
      login-processing-url: /api/user/login
    logout:
      logout-url: /api/user/logout
      delete-cookies:
        - SESSION